version: 2
updates:
    -   package-ecosystem: "gradle"
        directories:
            - "/"
        schedule:
            interval: "weekly"
            day: "tuesday"
            time: "09:00"
        target-branch: "develop"
        groups:
            all-gradle-deps:
                patterns:
                    - "*"

    -   package-ecosystem: "gradle"
        directories:
            - "/"
        schedule:
            interval: "weekly"
            day: "tuesday"
            time: "09:15"
        target-branch: "support/4.x"
        groups:
            all-gradle-deps:
                patterns:
                    - "*"
        ignore:
            -   dependency-name: "org.apache.groovy:groovy"
                versions: [ ">=5.0.0" ]
            -   dependency-name: "org.apache.groovy:groovy-all"
                versions: [ ">=5.0.0" ]
            -   dependency-name: "org.apache.groovy:groovy-sql"
                versions: [ ">=5.0.0" ]
            -   dependency-name: "*org.springframework.boot*"
                versions: [ ">=4.0.0" ]
            -   dependency-name: "org.springframework:*"
                versions: [ ">=7.0.0" ]
            -   dependency-name: "org.springframework.security:*"
                versions: [ ">=7.0.0" ]
            -   dependency-name: "org.springframework.data:*"
                versions: [ ">=4.0.0" ]
            -   dependency-name: "org.springframework.ldap:*"
                versions: [ ">=4.0.0" ]
            -   dependency-name: "org.mybatis:mybatis-spring"
                versions: [ ">=4.0.0" ]
            -   dependency-name: "org.junit.jupiter:junit-jupiter-engine"
                versions: [ ">=6.0.0" ]

    - package-ecosystem: "npm" # See documentation for possible values
      directories: # Location of package manifests
          - "/studio-ui"
          - "/js-sdk"
          - "/social/ui"
          - "/social/ui2"
      schedule:
          interval: "weekly"
          day: "wednesday"
          time: "09:00"
      target-branch: "develop"
      groups:
          all-ui-deps:
              patterns:
                  - "*"
    - package-ecosystem: "npm" # See documentation for possible values
      directories: # Location of package manifests
          - "/studio-ui"
          - "/js-sdk"
          - "/social/ui"
          - "/social/ui2"
      schedule:
        interval: "weekly"
        day: "wednesday"
        time: "09:15"
      target-branch: "support/4.x"
      groups:
          all-ui-deps:
              patterns:
              - "*"
