name: Enhancement Request
description: Request an enhancement
labels: ["enhancement", "triage"]
body:
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: The issue is in the latest released 4.1.x
        - label: The issue is in the latest released 4.0.x
        - label: The issue is in the latest released 3.1.x

  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the enhancement in the title above.

  - type: checkboxes
    attributes:
      label: Duplicates
      description: Please [search the history](https://github.com/craftercms/craftercms/issues) to see if an issue already exists for the same enhancement request.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: motivation
    attributes:
      label: Is your enhancement request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: What is the motivation for the enhancement?
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen and any alternatives you've considered.
      placeholder: What should CrafterCMS do?
    validations:
      required: true
