name: Feature Request
description: Request a new feature
labels: ["new feature", "triage"]
body:
  - type: input
    attributes:
      label: CI Number
      description: |
        Enter the CI number if known. This is the number that is generated when you create a support ticket.
      placeholder: N/A

  - type: input
    attributes:
      label: CI Number
      description: |
        Enter the CI number if known. This is the number that is generated when you create a support ticket.
      placeholder: N/A
  - type: checkboxes
    attributes:
      label: Duplicates
      description: Please [search the history](https://github.com/craftercms/craftercms/issues) to see if an issue already exists for the same feature request.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: motivation
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: What is the motivation for the new feature?
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen and any alternatives you've considered.
      placeholder: What should CrafterCMS do?
    validations:
      required: true
