/*
 * Copyright (C) 2007-2026 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

plugins {
	id 'java-library'
}

ext.crafterManifestTitle = 'Crafter Commons Validation'

apply from: "${rootDir}/gradle/java-library.gradle"

base {
	archivesName = 'crafter-commons-validation'
}

dependencies {
	api project(':commons:utilities')

	implementation libs.commons.lang3
	implementation libs.jakarta.validation.api
	implementation("org.owasp.esapi:esapi:${libs.versions.esapi.get()}:jakarta") {
		// Keep standalone Xerces out of the published POM; it breaks OpenSAML's parser pool
		exclude group: 'xerces', module: 'xercesImpl'
		exclude group: 'xml-apis', module: 'xml-apis'
	}
	implementation libs.hibernate.validator
	implementation libs.spring.context
	implementation libs.spring.context.support
	implementation libs.spring.web
	implementation libs.spring.webmvc
	implementation libs.jackson.databind
	implementation libs.jackson.core
	implementation libs.aspectjrt
	implementation libs.aspectjweaver

	testImplementation libs.junit
	testImplementation libs.mockito.core
	testImplementation libs.jakarta.servlet.api
}
